Repository DTStack/Taier, pull requests merged in 2022-04, with the labels that each got.

#328 [feat_hive][taier-ui]support to create hiveSQL task
  taier-ui/src/components/task/open.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/languages/index.tsx
Labels: feature

#332 [fix_task][taier-ui]improve ui interface
  taier-ui/src/components/markdown/index.scss
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/pages/operation/taskJobFlowView/index.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/styles/molecule.scss
  taier-ui/src/utils/competion.ts
  taier-ui/src/utils/index.ts
Labels: bug, feature

#335 [fix_ui][taier-ui]improve ui interface
  taier-ui/package.json
  taier-ui/src/components/spreadSheet/index.scss
  taier-ui/src/components/spreadSheet/index.tsx
  taier-ui/src/components/task/schedulingConfig/index.tsx
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.scss
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/index.scss
  taier-ui/src/pages/dataSource/index.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/styles/molecule.scss
  taier-ui/src/styles/reset.scss
  taier-ui/src/styles/variables.scss
  taier-ui/src/utils/copy.ts
  taier-ui/src/utils/index.ts
Labels: enhancement

#336 [feat_action][taier-ui]support to execute sql quickly
  taier-ui/src/extensions/action/index.ts
  taier-ui/src/extensions/action/quickRunSQLAction.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/index.ts
  taier-ui/src/utils/extensions.tsx
Labels: feature

#339 [fix_dataSync][taier-ui]fix datasync task
  taier-ui/src/components/dataSync/keymap.tsx
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
Labels: bug

#340 [fix_ui][taier-ui]improve the ui interface
  taier-ui/src/components/dataSync/index.scss
  taier-ui/src/components/dataSync/keymap.scss
  taier-ui/src/components/dataSync/keymap.tsx
  taier-ui/src/components/dataSync/modals/constModal.tsx
  taier-ui/src/components/task/schedulingConfig/taskDependence.tsx
  taier-ui/src/components/task/schedulingConfig/upstreamDependentTasks.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/styles/reset.scss
Labels: enhancement

#343 [fix_ui][taier-ui]improve the ui interface
  taier-ui/src/components/dataSync/index.tsx
  taier-ui/src/components/dataSync/keymap.tsx
  taier-ui/src/components/dataSync/modals/constModal.tsx
  taier-ui/src/components/dataSync/preview.tsx
Labels: enhancement

#346 [fix_ui][taier-ui]improve ui interface
  taier-ui/.umirc.ts
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/styles/reset.scss
Labels: enhancement

#348 [refactor_req][taier-ui]replace the increColumn request path
  taier-ui/src/api/reqOffline.ts
Labels: enhancement

#349 [refactor_req][taier-ui]replace the increColumn request path
  taier-ui/src/api/reqOffline.ts
  taier-ui/src/pages/console/cluster/newEdit/index.scss
Labels: bug

#353 [fix_dataSync][taier-ui]fix when change sourceId but still have columns in target
  taier-ui/src/components/dataSync/index.tsx
  taier-ui/src/components/dataSync/target.tsx
Labels: bug

#362 [fix_execute][taier-ui]remove log output when execute some command without result
  taier-ui/src/services/executeService.ts
Labels: enhancement

#365 [refactor_editor][taier-ui]replace codeMirror with monaco-editor
  taier-ui/.umirc.ts
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/components/editor/config.ts
  taier-ui/src/components/editor/index.tsx
  taier-ui/src/components/editor/language/jsonlog.ts
  taier-ui/src/components/editor/languages/dt-flink/dtflink.contribution.ts
  taier-ui/src/components/editor/languages/dt-flink/dtflink.ts
  taier-ui/src/components/editor/languages/dt-flink/dtflink.worker.ts
  taier-ui/src/components/editor/languages/dt-flink/simpleComplete.ts
  taier-ui/src/components/editor/languages/dtlog/dtlog.contribution.ts
  taier-ui/src/components/editor/languages/dtlog/dtlog.ts
  taier-ui/src/components/editor/languages/dtsql/dtsql.contribution.ts
  taier-ui/src/components/editor/languages/dtsql/dtsql.ts
  taier-ui/src/components/editor/languages/dtsql/dtsql.worker.ts
  taier-ui/src/components/editor/languages/dtsql/simpleComplete.ts
  taier-ui/src/components/editor/languages/shell/shell.contribution.ts
  taier-ui/src/components/editor/languages/shell/shell.ts
  taier-ui/src/components/editor/style.scss
  taier-ui/src/components/viewDetail/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/languages/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/kerberosModal/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskLog.tsx
Labels: refactor

#371 [feat_theme][taier-ui]improve dark theme in jobView
  taier-ui/src/components/mxGraph/index.scss
  taier-ui/src/components/slidePane/index.scss
  taier-ui/src/pages/operation/taskFlowView/taskGraphView.tsx
  taier-ui/src/pages/operation/taskJobFlowView/jobGraphView.tsx
  taier-ui/src/styles/common.scss
Labels: enhancement

#373 [fix_dirtyData][taier-ui]hide dirtyData for dataSync task
  taier-ui/src/components/dataSync/channel.tsx
Labels: refactor

#374 [fix_notification][taier-ui]improve the message tips and add a notification
  taier-ui/src/api/http.ts
  taier-ui/src/components/notification/index.tsx
  taier-ui/src/components/notification/notification.scss
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/pages/dataSource/index.tsx
  taier-ui/src/pages/dataSource/search.tsx
  taier-ui/src/pages/login.tsx
  taier-ui/src/styles/molecule.scss
  taier-ui/src/styles/reset.scss
Labels: enhancement, bug

#375 [build_ui][taier-ui]improve build process in Web
  taier-ui/.umirc.ts
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/src/components/codeEditor/config.ts
  taier-ui/src/components/codeEditor/index.tsx
  taier-ui/src/components/codeEditor/languages/log/index.ts
  taier-ui/src/components/codeEditor/languages/simpleLog/index.ts
  taier-ui/src/components/codeEditor/style.css
  taier-ui/src/components/codeEditor/utils.ts
  taier-ui/src/components/dataSync/preview.scss
  taier-ui/src/components/editor/diff.tsx
  taier-ui/src/components/editor/theme/whiteTheme.ts
  taier-ui/src/extensions/taier-theme/index.ts
  taier-ui/src/extensions/taier-theme/package.json
  taier-ui/src/extensions/taier-theme/themes/light_defaults.json
  taier-ui/src/extensions/taier-theme/themes/light_plus.json
  taier-ui/src/layout/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskLog.tsx
  taier-ui/src/reducer/catalogue/actionCreator.ts
  taier-ui/src/reducer/catalogue/actionTypes.ts
  taier-ui/src/reducer/catalogue/index.ts
  taier-ui/src/reducer/dataSync/actionType.ts
  taier-ui/src/reducer/dataSync/dataSync.ts
  taier-ui/src/reducer/dataSync/index.ts
  taier-ui/src/reducer/dataSync/offlineAction.tsx
  taier-ui/src/reducer/dataSync/tableType.ts
  taier-ui/src/reducer/dataSync/workbench.ts
  taier-ui/src/reducer/database/index.ts
  taier-ui/src/reducer/editor/actionTypes.ts
  taier-ui/src/reducer/editor/editorAction.ts
  taier-ui/src/reducer/editor/index.ts
  taier-ui/src/reducer/index.ts
  taier-ui/src/reducer/operation/actionType.ts
  taier-ui/src/reducer/operation/index.ts
  taier-ui/src/reducer/operation/operationAction.ts
  taier-ui/src/reducer/workbench/actinTypes.ts
  taier-ui/src/reducer/workbench/index.ts
  taier-ui/src/store/index.ts
  taier-ui/src/utils/index.ts
  taier-ui/src/utils/pureRender.ts
  taier-ui/typings.d.ts
Labels: enhancement

#376 [fix_ui][taier-ui]improve ui interface
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/src/api/http.ts
  taier-ui/src/components/editor/config.ts
  taier-ui/src/components/functionManager/fnViewModal.tsx
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/components/notification/index.tsx
  taier-ui/src/components/task/schedulingConfig/index.tsx
  taier-ui/src/extensions/action/quickRunSQLAction.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/global.scss
  taier-ui/src/pages/console/resource.scss
  taier-ui/src/pages/dataSource/InfoConfig/index.scss
  taier-ui/src/pages/dataSource/InfoConfig/index.tsx
  taier-ui/src/pages/dataSource/add.scss
  taier-ui/src/pages/dataSource/selectSource.scss
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/login.scss
  taier-ui/src/pages/login.tsx
  taier-ui/src/services/editorActionBarService.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/services/index.ts
  taier-ui/src/styles/theme.scss
  taier-ui/src/utils/extensions.tsx
  taier-ui/tsconfig.json
Labels: enhancement

#382 [refactor_editor][taier-ui]use monaco-editor instead of codeMirror
  taier-ui/package.json
  taier-ui/src/components/editor/index.tsx
  taier-ui/src/components/editor/language/jsonlog.ts
  taier-ui/src/components/logEditor/index.tsx
  taier-ui/src/components/markdown/index.scss
  taier-ui/src/components/slidePane/index.tsx
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/extensions/init.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskLog.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/services/taskResultService.ts
  taier-ui/src/utils/extensions.tsx
Labels: enhancement

#384 [refactor][taier-ui]improve UI interface
  taier-ui/src/components/dataSync/index.tsx
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/components/detailInfo/index.scss
  taier-ui/src/components/detailInfo/index.tsx
  taier-ui/src/components/editor/index.tsx
  taier-ui/src/components/editorEntry/index.scss
  taier-ui/src/components/editorEntry/index.tsx
  taier-ui/src/components/functionManager/fnViewModal.scss
  taier-ui/src/components/functionManager/fnViewModal.tsx
  taier-ui/src/components/resourceManager/resViewModal.scss
  taier-ui/src/components/resourceManager/resViewModal.tsx
  taier-ui/src/components/task/open.tsx
  taier-ui/src/components/task/schedulingConfig/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/rightBar/taskInfo.scss
  taier-ui/src/pages/rightBar/taskInfo.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/services/taskResultService.ts
  taier-ui/src/styles/molecule.scss
  taier-ui/src/styles/reset.scss
  taier-ui/src/utils/saveTask.ts
Labels: enhancement

#387 [fix_ui][taier-ui]support flinkSQL
  taier-ui/src/api/reqStream.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/editorEntry/index.tsx
  taier-ui/src/components/folderPicker/index.tsx
  taier-ui/src/components/functionManager/fnModal.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/action/index.ts
  taier-ui/src/extensions/action/quickSaveTaskAction.ts
  taier-ui/src/extensions/catalogue/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/services/editorActionBarService.tsx
  taier-ui/src/utils/extensions.tsx
  taier-ui/src/utils/saveTask.ts
Labels: feature

#344 [feat_taskManage][taier-ui]add taskManage
  taier-ui/src/api/reqStream.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/fullScreen/icon.tsx
  taier-ui/src/components/fullScreen/index.tsx
  taier-ui/src/components/fullScreen/listener.tsx
  taier-ui/src/components/graphTime/constants.ts
  taier-ui/src/components/graphTime/graphTimePicker.tsx
  taier-ui/src/components/graphTime/graphTimeRange.tsx
  taier-ui/src/components/graphTime/style.scss
  taier-ui/src/components/svgIcon/index.tsx
  taier-ui/src/components/svgIcon/style.scss
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/menu/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/baseGraph.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/dataDelay.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/delay/detailGraph.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/delay/detailTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/help.ts
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/metricSelect/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/metricSelect/style.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/address.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/resultTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/checkPoint.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/failover.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/historyLog.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/logInfo.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/detailTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/graphEditor.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/list.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/log.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx
  taier-ui/src/pages/operation/streamTask/components/goOnTask.tsx
  taier-ui/src/pages/operation/streamTask/components/reRunModal.scss
  taier-ui/src/pages/operation/streamTask/components/reRunModal.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/utils/index.ts
Labels: feature

#390 [fix_ui][taier-ui]improve ui interface
  taier-ui/src/api/reqStream.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/customHooks/useCalcTableScroll.ts
  taier-ui/src/components/folderPicker/customTreeSelect.tsx
  taier-ui/src/components/folderPicker/index.tsx
  taier-ui/src/components/functionManager/fnModal.tsx
  taier-ui/src/components/functionManager/index.tsx
  taier-ui/src/components/helpDoc/docs.tsx
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/components/resourceManager/index.tsx
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkResult/form.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkResult/index.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkSource/form.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkSource/index.tsx
  taier-ui/src/components/task/envParams.tsx
  taier-ui/src/components/task/schedulingConfig/index.tsx
  taier-ui/src/components/task/schedulingConfig/taskDependence.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/action/quickRunSQLAction.ts
  taier-ui/src/extensions/action/quickSaveTaskAction.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/extensions/init.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/console/cluster/newEdit/index.tsx
  taier-ui/src/pages/dataSource/add.tsx
  taier-ui/src/pages/dataSource/index.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/operation/patch/detail.tsx
  taier-ui/src/pages/operation/schedule.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/index.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/address.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/resultTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/failover.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/historyLog.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/logInfo.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/detailTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/graphEditor.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/index.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/list.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/log.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskLog.tsx
  taier-ui/src/pages/rightBar/index.tsx
  taier-ui/src/services/editorActionBarService.tsx
  taier-ui/src/services/executeService.ts
  taier-ui/src/styles/common.scss
  taier-ui/src/styles/reset.scss
  taier-ui/src/utils/extensions.tsx
  taier-ui/src/utils/saveTask.ts
Labels: enhancement, bug

#393 [feat_1.1_dev_streamCollection][taier-ui]support stream collection task
  taier-ui/.umirc.ts
  taier-ui/src/api/defaultParams.ts
  taier-ui/src/api/reqStream.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/detailInfo/index.tsx
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/components/streamCollection/channel/index.tsx
  taier-ui/src/components/streamCollection/complete/index.tsx
  taier-ui/src/components/streamCollection/index.scss
  taier-ui/src/components/streamCollection/rightBar/streamSetting/index.scss
  taier-ui/src/components/streamCollection/rightBar/streamSetting/index.tsx
  taier-ui/src/components/streamCollection/rightBar/streamSetting/wrappedForm.tsx
  taier-ui/src/components/streamCollection/source/component/emq.tsx
  taier-ui/src/components/streamCollection/source/component/kafka.tsx
  taier-ui/src/components/streamCollection/source/component/rdb.tsx
  taier-ui/src/components/streamCollection/source/component/socket.tsx
  taier-ui/src/components/streamCollection/source/component/websocket.tsx
  taier-ui/src/components/streamCollection/source/index.tsx
  taier-ui/src/components/streamCollection/steps.tsx
  taier-ui/src/components/streamCollection/targetSource/component/adb.tsx
  taier-ui/src/components/streamCollection/targetSource/component/kafka.tsx
  taier-ui/src/components/streamCollection/targetSource/index.tsx
  taier-ui/src/components/streamCollection/taskFunc.tsx
  taier-ui/src/components/task/open.tsx
  taier-ui/src/components/task/publish.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/pages/rightBar/index.tsx
  taier-ui/src/services/editorActionBarService.tsx
  taier-ui/src/utils/extensions.tsx
  taier-ui/src/utils/saveTask.ts
Labels: enhancement

#394 [fix_ui][taier-ui]improve ui interface
  taier-ui/src/api/reqOffline.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/language/index.tsx
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/components/slidePane/index.scss
  taier-ui/src/components/streamCollection/rightBar/flinkDimension/index.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkResult/index.tsx
  taier-ui/src/components/streamCollection/rightBar/flinkSource/index.tsx
  taier-ui/src/components/streamCollection/rightBar/streamSetting/index.tsx
  taier-ui/src/components/streamCollection/taskFunc.tsx
  taier-ui/src/components/task/envParams.tsx
  taier-ui/src/components/task/open.tsx
  taier-ui/src/components/task/schedulingConfig/index.tsx
  taier-ui/src/components/task/taskParams.tsx
  taier-ui/src/extensions/action/quickRunSQLAction.ts
  taier-ui/src/extensions/action/quickSaveTaskAction.ts
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/list.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/log.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/taskManager/log.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/pages/rightBar/index.tsx
  taier-ui/src/pages/rightBar/taskInfo.tsx
  taier-ui/src/utils/enums.tsx
Labels: bug

#395 [fix_1.1_dev_startTask][taier-ui]fix: fix antd dark style and start stream task
  taier-ui/src/extensions/init.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/styles/reset.scss
Labels: bug

#397 [fix_status][taier-ui]add task status
  taier-ui/.umirc.ts
  taier-ui/src/constant/index.ts
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx
  taier-ui/src/utils/enums.tsx
Labels: bug

#398 [fix_ui][taier-ui]improve ui interface
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/hooks/index.ts
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runCode/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/historyLog.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runLog/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/index.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/styles/reset.scss
Labels: enhancement

#400 [fix_ui][taier-ui]support continue running task
  taier-ui/src/api/reqStream.ts
  taier-ui/src/api/stream.ts
  taier-ui/src/components/slidePane/index.scss
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/pages/operation/patch/patchModal.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/detailGraph/baseGraph.tsx
  taier-ui/src/pages/operation/streamTask/components/goOnTask.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/styles/reset.scss
Labels: enhancement
