Repository DTStack/Taier, pull requests merged in 2022-07, with the labels that each got.

#617 [feat_schema][taier-ui]support to configurate schema for task component
  taier-ui/src/api/http.ts
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/addTenantModal/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/init.tsx
  taier-ui/src/pages/account/schemaModal.tsx
Labels: feature

#616 [feat/function][taier-ui]improve function manager folder
  taier-ui/src/pages/function/index.tsx
Labels: feature

#618 [improvement][taier-ui]have a log when template request incorrect data
  taier-ui/src/extensions/themes/githubPlus.json
  taier-ui/src/pages/console/cluster/nextDetail/index.tsx
Labels: enhancement

#606 [task_config][taier-ui]support task config in rightbar
  taier-ui/public/layout/rightBar.json
  taier-ui/src/api/index.ts
  taier-ui/src/components/helpDoc/docs.tsx
  taier-ui/src/components/lifeCycleSelect/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/editor/dataSync/index.tsx
  taier-ui/src/pages/rightBar/taskConfig.tsx
  taier-ui/src/services/rightBarService.tsx
  taier-ui/src/utils/saveTask.ts
Labels: feature

#620 [feat/oceanbase][taier-ui]support to get task text via request
  taier-ui/public/layout/editorActions.json
  taier-ui/public/layout/rightBar.json
  taier-ui/src/components/detailInfo/index.tsx
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/components/language/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/context/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/extensions/languages/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/function/fnModal.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/operation/patch/detail.tsx
  taier-ui/src/pages/operation/patch/patchModal.tsx
  taier-ui/src/pages/operation/schedule.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/pages/operation/task.tsx
  taier-ui/src/pages/operation/taskFlowView/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/index.tsx
  taier-ui/src/pages/resource/resModal.tsx
  taier-ui/src/services/taskRenderService.tsx
  taier-ui/src/utils/enums.tsx
Labels: enhancement

#621 [feat/resource][taier-ui]support to get resource location
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/folderPicker/index.tsx
Labels: bug

#623 [feat_selectStatus][taier-ui]improve selectStatus
  taier-ui/src/services/executeService.ts
Labels: enhancement

#625 [feat_1.2_addLogin][taier-ui] add loginModal in statusBar
  taier-ui/src/extensions/init.tsx
Labels: enhancement

#624 [feat_render][taier-ui]improve taskRender
  taier-ui/.umirc.ts
  taier-ui/public/images/points.gif
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/folderPicker/index.tsx
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/components/mxGraph/container.scss
  taier-ui/src/components/mxGraph/container.tsx
  taier-ui/src/components/mxGraph/index.tsx
  taier-ui/src/components/scaffolds/create.tsx
  taier-ui/src/extensions/action/quickSaveTaskAction.ts
  taier-ui/src/extensions/dtstackTheme/index.ts
  taier-ui/src/extensions/dtstackTheme/package.json
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/editor/dataSync/index.tsx
  taier-ui/src/pages/editor/streamCollection/index.tsx
  taier-ui/src/pages/editor/virtual.tsx
  taier-ui/src/pages/rightBar/flinkSource/form.tsx
  taier-ui/src/pages/rightBar/schedulingConfig/taskDependence.tsx
  taier-ui/src/services/rightBarService.tsx
  taier-ui/src/services/taskRenderService.tsx
  taier-ui/src/services/taskSaveService.ts
  taier-ui/src/services/viewStoreService.ts
  taier-ui/src/utils/enums.tsx
  taier-ui/src/utils/extensions.tsx
  taier-ui/src/utils/index.ts
  taier-ui/src/utils/saveTask.ts
Labels: enhancement

#626 [fix/result][taier-ui]fix getting result for executed task
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/src/services/executeService.ts
  taier-ui/src/services/taskResultService.ts
  taier-ui/src/utils/extensions.tsx
Labels: bug

#628 fix: support abort request in dataSync
  taier-ui/.umirc.ts
  taier-ui/src/api/http.ts
  taier-ui/src/api/index.ts
  taier-ui/src/extensions/languages/index.tsx
  taier-ui/src/pages/editor/dataSync/keymap.tsx
  taier-ui/src/pages/editor/dataSync/source.tsx
  taier-ui/src/pages/editor/dataSync/target.tsx
  taier-ui/src/services/taskRenderService.tsx
Labels: enhancement

#630 [feat_workflow_ui][taier-ui]develop workflow task
  taier-ui/public/layout/create.json
  taier-ui/public/layout/editorActions.json
  taier-ui/public/layout/rightBar.json
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/mxGraph/container.tsx
  taier-ui/src/components/task/create.tsx
  taier-ui/src/extensions/action/quickSaveTaskAction.ts
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/extensions/themes/githubPlus.json
  taier-ui/src/interface.ts
  taier-ui/src/layout/index.tsx
  taier-ui/src/pages/console/cluster/nextDetail/index.tsx
  taier-ui/src/pages/editor/dataSync/index.tsx
  taier-ui/src/pages/editor/flink.tsx
  taier-ui/src/pages/editor/virtual.tsx
  taier-ui/src/pages/editor/workflow/index.scss
  taier-ui/src/pages/editor/workflow/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.tsx
  taier-ui/src/services/taskRenderService.tsx
  taier-ui/src/services/taskSaveService.ts
  taier-ui/src/services/viewStoreService.ts
Labels: feature

#633 fix: support dispatch support jobs in cluster
  taier-ui/src/components/task/create.tsx
  taier-ui/src/context/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/hooks/index.ts
  taier-ui/src/pages/console/cluster/nextDetail/index.tsx
  taier-ui/src/pages/console/cluster/nextDetail/sideBar.tsx
  taier-ui/src/pages/index.tsx
Labels: bug

#634 fix: support show tenant list without engine
  taier-ui/src/pages/console/resource.tsx
Labels: bug

#635 [refactor][taier-ui]remove code and rename nextDetail to detail
  taier-ui/src/pages/console/cluster/detail/detail.scss
  taier-ui/src/pages/console/cluster/detail/detail.tsx
  taier-ui/src/pages/console/cluster/detail/index.scss
  taier-ui/src/pages/console/cluster/detail/index.tsx
  taier-ui/src/pages/console/cluster/detail/sideBar.scss
  taier-ui/src/pages/console/cluster/detail/sideBar.tsx
  taier-ui/src/pages/console/cluster/detail/toolbar.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/compsBtn/index.scss
  taier-ui/src/pages/console/cluster/newEdit/components/compsBtn/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/metaIcon/index.scss
  taier-ui/src/pages/console/cluster/newEdit/components/metaIcon/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.scss
  taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/singleVerComp/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/components/toolbar/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/context.ts
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/dataCheckbox/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/defaultVersionCheckbox/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/kerberosModal/index.scss
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/kerberosModal/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/uploadFileBtn/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/index.scss
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/formConfig/components/customParams/index.scss
  taier-ui/src/pages/console/cluster/newEdit/formConfig/components/customParams/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/formConfig/index.scss
  taier-ui/src/pages/console/cluster/newEdit/formConfig/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/help.ts
  taier-ui/src/pages/console/cluster/newEdit/index.scss
  taier-ui/src/pages/console/cluster/newEdit/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/interface.ts
  taier-ui/src/pages/index.tsx
Labels: refactor

#637 fix: publish no longer need description
  taier-ui/src/components/task/publish.tsx
  taier-ui/src/extensions/editor/index.tsx
Labels: refactor

#638 [refactor][taier-ui]improve workflow vertex theme
  taier-ui/src/components/mxGraph/container.tsx
  taier-ui/src/components/mxGraph/index.tsx
  taier-ui/src/components/task/publish.tsx
  taier-ui/src/extensions/themes/githubPlus.json
  taier-ui/src/extensions/themes/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/editor/workflow/index.scss
  taier-ui/src/pages/editor/workflow/index.tsx
  taier-ui/src/services/taskSaveService.ts
Labels: bug, refactor

#641 [fix/flinksql][taier-ui]fix flinksql save failed
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/pages/console/cluster/detail/index.tsx
  taier-ui/src/pages/rightBar/flinkDimension/form.tsx
  taier-ui/src/pages/rightBar/flinkDimension/index.tsx
  taier-ui/src/pages/rightBar/flinkResult/form.tsx
  taier-ui/src/pages/rightBar/flinkResult/index.tsx
  taier-ui/src/services/taskSaveService.ts
Labels: bug

#643 [feat/function][taier-ui]support to create hivesql function
  taier-ui/src/components/detailInfo/index.tsx
  taier-ui/src/components/folderPicker/customTreeSelect.tsx
  taier-ui/src/components/folderPicker/index.tsx
  taier-ui/src/components/scaffolds/create.tsx
  taier-ui/src/components/task/create.tsx
  taier-ui/src/components/task/editFolder.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/pages/function/fnModal.tsx
  taier-ui/src/pages/function/folderModal.tsx
  taier-ui/src/pages/function/index.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
  taier-ui/src/pages/operation/task.tsx
  taier-ui/src/pages/resource/index.tsx
  taier-ui/src/pages/resource/resModal.tsx
  taier-ui/src/pages/rightBar/taskInfo.tsx
  taier-ui/src/services/breadcrumbService.ts
  taier-ui/src/services/catalogueService.ts
  taier-ui/src/utils/extensions.tsx
Labels: feature, refactor

#642 [feat/workflow][taier-ui]support workflow job and task in operation
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/mxGraph/container.tsx
  taier-ui/src/components/mxGraph/index.scss
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/operation/patch/detail.tsx
  taier-ui/src/pages/operation/schedule.tsx
  taier-ui/src/pages/operation/task.tsx
  taier-ui/src/pages/operation/taskFlowView/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/index.tsx
  taier-ui/src/utils/index.ts
Labels: feature

#647 fix: improve table width in queue
  taier-ui/src/pages/console/queue.tsx
  taier-ui/src/pages/console/taskDetail.tsx
Labels: bug

#646 fix: prevent workflow related task change schedule config
  taier-ui/src/pages/rightBar/schedulingConfig/index.tsx
  taier-ui/src/pages/rightBar/schedulingConfig/scheduleForm.tsx
Labels: bug

#649 [fix/workflow][taier-ui]fix workflow save
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/mxGraph/index.scss
  taier-ui/src/components/mxGraph/index.tsx
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/themes/defaultDark.json
  taier-ui/src/extensions/themes/defaultLight.json
  taier-ui/src/extensions/themes/index.tsx
  taier-ui/src/layout/index.tsx
  taier-ui/src/pages/editor/workflow/index.tsx
  taier-ui/src/pages/operation/patch/detail.tsx
  taier-ui/src/pages/operation/schedule.tsx
  taier-ui/src/pages/operation/taskFlowView/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/index.scss
  taier-ui/src/pages/operation/taskJobFlowView/index.tsx
  taier-ui/src/pages/rightBar/taskConfig.tsx
  taier-ui/src/services/taskSaveService.ts
  taier-ui/src/utils/index.ts
Labels: bug

#651 [fix/theme][taier-ui]improve scroll theme
  taier-ui/src/components/editor/index.tsx
  taier-ui/src/components/editor/language/jsonlog.ts
  taier-ui/src/extensions/themes/defaultDark.json
  taier-ui/src/extensions/themes/defaultLight.json
Labels: bug
