Repository DTStack/Taier, pull requests merged in 2022-11, with the labels that each got.

#833 [fix/cluster][taier-ui]support more impressive error log
  taier-ui/src/pages/console/cluster/detail/index.tsx
  taier-ui/src/pages/console/cluster/detail/toolbar.tsx
Labels: enhancement

#834 [fix/execute][taier-ui]fix log output panel after executing
  taier-ui/src/services/executeService.ts
  taier-ui/src/utils/extensions.tsx
Labels: bug

#840 [fix/stream][taier-ui]remove component version filters in stream
  taier-ui/src/pages/operation/streamTask/index.tsx
Labels: bug

#835 [fix/flink][taier-ui]fix validation on flinksql
  taier-ui/src/pages/rightBar/flinkDimension/index.tsx
  taier-ui/src/pages/rightBar/flinkResult/index.tsx
  taier-ui/src/pages/rightBar/flinkSource/index.tsx
Labels: bug

#870 [feat/website][taier-ui]replace case image
  website/static/img/assets/stream.png
Labels: documentation

#873 [doc/readme][taier]translate README into English
  README _zh-CN.md
  README.md
Labels: documentation

#865 [hotfix][taier-docs] taier源码包下载地址不对
  website/docs/quickstart/deploy/deployment-quick.md
Labels: bug

#872 [hotfix_871][taier-worker-plugin] script-core build Dir is error
  taier-worker/taier-worker-plugin/script/yarn2-hdfs2-script/script-core/pom.xml
  taier-worker/taier-worker-plugin/script/yarn3-hdfs3-script/script-core/pom.xml
Labels: bug

#886 [feat/cluster][taier-ui]improve description label in cluster's uploader
  taier-ui/src/constant/index.ts
  taier-ui/src/pages/console/cluster/detail/detail.tsx
Labels: documentation

#902 [fix/schedule][taier-ui]support render deleted task in schedule
  taier-ui/src/interface.ts
  taier-ui/src/pages/operation/schedule.tsx
Labels: bug

#909 [fix/envParams][taier-ui]fix cursor always in first time on envParams
  taier-ui/src/pages/rightBar/envParams.tsx
Labels: bug

#917 [fix/testConn][taier-ui]fix message.error in twice
  taier-ui/src/pages/dataSource/add.tsx
Labels: bug

#913 [Feature] Add Oracle Datasource Plugin
  taier-datasource/taier-datasource-plugin/pom.xml
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/pom.xml
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleClient.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleConnFactory.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleDbAdapter.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleDownloader.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleErrorPattern.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/OracleTableClient.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/java/com/dtstack/taier/datasource/plugin/oracle/SqlConstant.java
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/resources/META-INF/services/com.dtstack.taier.datasource.api.client.IClient
  taier-datasource/taier-datasource-plugin/taier-datasource-plugin-oracle/src/main/resources/META-INF/services/com.dtstack.taier.datasource.api.client.ITable
  website/docs/quickstart/build.md
Labels: feature
