Repository DTStack/Taier, pull requests merged in 2022-12, with the labels that each got.

#911 [feat/ftp][taier-ui]support ftp in reader and writer
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/components/lineTo/index.tsx
  taier-ui/src/components/scaffolds/task.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/interface.ts
  taier-ui/src/pages/editor/dataSync/index.tsx
  taier-ui/src/pages/editor/dataSync/keyMap.scss
  taier-ui/src/pages/editor/dataSync/keyMap.tsx
  taier-ui/src/pages/editor/dataSync/modals/keyModal.tsx
  taier-ui/src/pages/editor/dataSync/tableFooter.scss
  taier-ui/src/pages/editor/dataSync/tableFooter.tsx
  taier-ui/src/services/taskSaveService.ts
Labels: feature

#937 fixed: 1.3.1 increment sql merged(#936)
  sql/1.3.1/1.3.1_increment.sql
  sql/1.3.1/increment.sql
Labels: refactor

#943 fixed: ftp target index #938 no initial value given
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/DevelopTaskService.java
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/template/ftp/FTPColumn.java
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/template/ftp/FTPWriteParam.java
Labels: bug

#941 fix: table render in FTP target
  taier-ui/src/components/scaffolds/task.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/editor/dataSync/keyMap.tsx
Labels: bug

#950 [refactor][taier-ui]parse task variables by editor's value in default
  taier-ui/src/extensions/editor/index.tsx
Labels: refactor

#949 [style/utils][taier-ui]remove unused functions
  taier-ui/src/utils/__tests__/enums.test.tsx
  taier-ui/src/utils/__tests__/index.test.tsx
  taier-ui/src/utils/enums.tsx
  taier-ui/src/utils/index.ts
Labels: Improve

#953 [fix/create][taier-ui]fix create folder failed
  taier-ui/src/extensions/folderTree/index.tsx
Labels: bug

#955 [feat/icon][taier-ui]add several icons
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/services/taskRenderService.tsx
Labels: feature

#956 [refactor/upstream][taier-ui]improve the upstream default options
  taier-ui/src/pages/rightBar/schedulingConfig/upstreamDependentTasks.tsx
  taier-ui/src/styles/reset.scss
Labels: Improve

#958 build: bump molecule's version to 1.3.0
  taier-ui/.umirc.ts
  taier-ui/pnpm-lock.yaml
  taier-ui/scripts/sync-workbench.js
  taier-ui/src/components/task/editFolder.tsx
  taier-ui/src/components/task/result.tsx
  taier-ui/src/extensions/auxiliaryBar/index.tsx
  taier-ui/src/extensions/index.ts
  taier-ui/src/pages/dataSource/add.tsx
  taier-ui/src/pages/editor/dataSync/index.tsx
  taier-ui/src/pages/editor/streamCollection/index.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/rightBar/flinkDimension/index.tsx
  taier-ui/src/pages/rightBar/flinkResult/index.tsx
  taier-ui/src/pages/rightBar/flinkSource/index.tsx
  taier-ui/src/pages/rightBar/index.scss
  taier-ui/src/pages/rightBar/index.tsx
  taier-ui/src/pages/rightBar/schedulingConfig/index.tsx
  taier-ui/src/pages/rightBar/taskConfig.tsx
  taier-ui/src/pages/rightBar/taskParams.tsx
  taier-ui/src/pages/workbench.tsx
  taier-ui/src/services/rightBarService.tsx
  taier-ui/src/styles/molecule.scss
Labels: refactor

#957 [feat/selection][taier-ui]support run sql in selection
  taier-ui/src/context/index.ts
  taier-ui/src/interface.ts
  taier-ui/src/services/taskRenderService.tsx
  taier-ui/src/utils/extensions.tsx
Labels: enhancement
