Repository DTStack/Taier, pull requests merged in 2022-06, with the labels that each got.

#571 [fix_operation][taier-ui]fix disabled buttons can still be clicked
  taier-ui/src/extensions/editor/index.tsx
Labels: bug

#573 [fix_polling][taier-ui]fix polling pagination error
  taier-ui/src/components/sketch/index.tsx
  taier-ui/src/hooks/index.ts
  taier-ui/src/pages/operation/patch/detail.tsx
  taier-ui/src/pages/operation/streamTask/index.tsx
Labels: bug

#572 [test/utils][taier-ui]add test cases for utils
  taier-ui/__mocks__/molecule.js
  taier-ui/__mocks__/monaco-editor.js
  taier-ui/jest.config.js
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/scripts/jest-setup.js
  taier-ui/src/utils/__tests__/__snapshots__/enums.test.tsx.snap
  taier-ui/src/utils/__tests__/enums.test.tsx
  taier-ui/src/utils/__tests__/index.test.tsx
  taier-ui/src/utils/__tests__/is.test.tsx
  taier-ui/src/utils/is.ts
Labels: test

#581 [issue_580][taier] fix sync job run log download #580
  taier-data-develop/src/main/java/com/dtstack/taier/develop/controller/develop/DevelopDownloadController.java
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/MultiEngineServiceFactory.java
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchCatalogueService.java
  taier-data-develop/src/main/java/com/dtstack/taier/develop/service/develop/impl/BatchHadoopSelectSqlService.java
Labels: bug

#578 [feat_cluster][taier-ui]support render tooltip for cluster form field
  taier-ui/src/pages/console/cluster/newEdit/formConfig/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/interface.ts
Labels: feature

#582 [refactor][taier-ui]refactor mxGraph usage
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/public/images/sent.svg
  taier-ui/src/components/mxGraph/container.scss
  taier-ui/src/components/mxGraph/container.tsx
  taier-ui/src/components/mxGraph/index.scss
  taier-ui/src/components/mxGraph/index.ts
  taier-ui/src/components/mxGraph/index.tsx
  taier-ui/src/components/mxGraph/mxEdgeStyle/index.ts
  taier-ui/src/components/statusColumn/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/common.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/detailTable.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/graphEditor.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/index.tsx
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.scss
  taier-ui/src/pages/operation/streamTask/components/detailPane/components/runMsg/linkDiagram.tsx
  taier-ui/src/pages/operation/taskFlowView/index.tsx
  taier-ui/src/pages/operation/taskFlowView/taskGraphView.tsx
  taier-ui/src/pages/operation/taskJobFlowView/index.scss
  taier-ui/src/pages/operation/taskJobFlowView/index.tsx
  taier-ui/src/pages/operation/taskJobFlowView/jobGraphView.scss
  taier-ui/src/pages/operation/taskJobFlowView/jobGraphView.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskInfo.tsx
  taier-ui/src/pages/operation/taskJobFlowView/taskLog.tsx
  taier-ui/src/styles/common.scss
  taier-ui/src/utils/enums.tsx
  taier-ui/tsconfig.json
Labels: enhancement

#598 [fix_resource][taier-ui]improve resouce binding tenant
  taier-ui/src/components/bindCommModal/index.tsx
  taier-ui/src/components/resourceManageModal/index.tsx
  taier-ui/src/pages/console/bindTenant.tsx
  taier-ui/src/pages/console/resource.tsx
  taier-ui/src/pages/console/resourceView/index.tsx
Labels: enhancement

#597 [feat/cluster][taier-ui]refactor cluster
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
  taier-ui/src/context/cluster.ts
  taier-ui/src/pages/console/cluster/nextDetail/detail.scss
  taier-ui/src/pages/console/cluster/nextDetail/detail.tsx
  taier-ui/src/pages/console/cluster/nextDetail/index.scss
  taier-ui/src/pages/console/cluster/nextDetail/index.tsx
  taier-ui/src/pages/console/cluster/nextDetail/sideBar.scss
  taier-ui/src/pages/console/cluster/nextDetail/sideBar.tsx
  taier-ui/src/pages/console/cluster/nextDetail/toolbar.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/styles/reset.scss
Labels: refactor

#599 [fix/queue][taier-ui]fix request lost
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
Labels: bug

#602 [feat/flink][taier-ui]support create flink task
  taier-ui/src/components/task/open.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/folderTree/index.tsx
Labels: feature

#604 [build/molecule][taier-ui]bump molecule's version to 1.0.2
  taier-ui/package.json
  taier-ui/pnpm-lock.yaml
  taier-ui/scripts/sync-workbench.js
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/extensions/init.tsx
  taier-ui/src/pages/index.tsx
  taier-ui/src/pages/workbench.tsx
Labels: enhancement

#607 [hotfix/request][taier-ui]add lost request
  taier-ui/src/api/index.ts
  taier-ui/src/api/request.ts
Labels: bug

#609 [feat_collapse][taier-ui]support expand default collapse
  taier-ui/src/extensions/init.tsx
Labels: enhancement

#610 [improvement][taier-ui]improve resouce manage
  taier-ui/src/pages/console/resource.scss
  taier-ui/src/pages/console/resource.tsx
  taier-ui/src/pages/console/resourceView/helper.tsx
  taier-ui/src/pages/console/resourceView/index.scss
  taier-ui/src/pages/console/resourceView/index.tsx
Labels: enhancement

#612 [style/theme][taier-ui]improve colorTheme in light
  taier-ui/src/components/mxGraph/index.scss
  taier-ui/src/extensions/dtstackTheme/index.ts
  taier-ui/src/extensions/dtstackTheme/package.json
  taier-ui/src/extensions/dtstackTheme/themes/dtstackTheme.json
  taier-ui/src/extensions/index.ts
  taier-ui/src/extensions/themes/githubPlus.json
  taier-ui/src/extensions/themes/index.tsx
  taier-ui/src/global.scss
Labels: enhancement
