Repository DTStack/Taier, pull requests merged in 2022-03, with the labels that each got.

#285 [fix_cluster][taier-ui]fix can't save hiveServer
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/dataCheckbox/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/fileConfig/components/defaultVersionCheckbox/index.tsx
Labels: bug

#276 [feat_collpase][taier-ui]support to collapse all files
  taier-ui/src/extensions/init.tsx
Labels: feature

#289 [fix_sketch][taier-ui]optimized schedule table scroll
  taier-ui/src/components/customHooks/index.ts
  taier-ui/src/components/customHooks/useCalcTableScroll.ts
  taier-ui/src/components/sketch/index.scss
  taier-ui/src/components/sketch/index.tsx
Labels: ui

#292 [fix_style][taier-ui]remove @ant-design/compatible
  taier-ui/package.json
  taier-ui/src/api/reqOffline.ts
  taier-ui/src/pages/index.tsx
  taier-ui/src/styles/reset.scss
Labels: refactor

#291 [fix_tableScroller][taier-ui]fix break when table without header or footer
  taier-ui/src/components/customHooks/useCalcTableScroll.ts
Labels: bug

#293 [feat_increment][taier-ui]support increment for dataSync
  taier-ui/src/components/dataSync/channel.tsx
  taier-ui/src/components/dataSync/index.tsx
  taier-ui/src/components/dataSync/interface.ts
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/components/helpDoc/docs.tsx
  taier-ui/src/components/task/open.tsx
Labels: feature

#296 [feat_createModal][taier-ui]support to set model for dataSync
  taier-ui/src/components/helpDoc/docs.tsx
  taier-ui/src/components/task/importTemplate.tsx
  taier-ui/src/components/task/open.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/extensions/languages/index.tsx
  taier-ui/src/interface.ts
  taier-ui/src/utils/extensions.tsx
Labels: feature

#305 [fix_ui][taier-ui]fix some details in UI interface
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/pages/dataSource/add.tsx
  taier-ui/src/pages/index.tsx
Labels: bug

#306 [fix_expandKeys][taier-ui]fix can't expand folders
  taier-ui/src/components/functionManager/index.tsx
  taier-ui/src/components/resourceManager/index.tsx
  taier-ui/src/services/functionManagerService.ts
  taier-ui/src/services/resourceManagerService.ts
Labels: bug

#310 [feat_dataSource][taier-ui]improve the dataSource
  taier-ui/src/components/icon/index.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/pages/dataSource/index.scss
  taier-ui/src/pages/dataSource/index.tsx
  taier-ui/src/styles/reset.scss
Labels: bug

#311 [fix_save][taier-ui]fix lost sqlText when saving
  taier-ui/src/components/dataSync/help.ts
  taier-ui/src/extensions/editor/index.tsx
Labels: bug

#312 [refactor_req][taier-ui]replace the path of offline request
  taier-ui/src/api/req.ts
  taier-ui/src/api/reqOffline.ts
  taier-ui/src/extensions/editor/index.tsx
Labels: refactor

#304 [feat_dataSync][taier-ui]support ES and HBASE dataSource in dataSync
  taier-ui/src/components/dataSync/help.ts
  taier-ui/src/components/dataSync/interface.ts
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/components/helpDoc/docs.tsx
  taier-ui/src/constant/index.ts
Labels: feature

#319 [fix_dataSync][taier-ui]improve dataSync params
  taier-ui/src/components/dataSync/channel.tsx
  taier-ui/src/components/dataSync/help.ts
  taier-ui/src/components/dataSync/index.tsx
  taier-ui/src/components/dataSync/interface.ts
  taier-ui/src/components/dataSync/keymap.tsx
  taier-ui/src/components/dataSync/modals/constModal.tsx
  taier-ui/src/components/dataSync/modals/keyModal.tsx
  taier-ui/src/components/dataSync/preview.tsx
  taier-ui/src/components/dataSync/source.tsx
  taier-ui/src/components/dataSync/target.tsx
  taier-ui/src/constant/index.ts
  taier-ui/src/extensions/editor/index.tsx
  taier-ui/src/extensions/folderTree/index.tsx
  taier-ui/src/interface.ts
Labels: refactor

#323 [build_hive][taier-ui]support build hivesql.worker
  taier-ui/.umirc.ts
Labels: bug

#326 [fix_cluster][taier-ui]fix multiply clusters have isMetadata
  taier-ui/src/pages/console/cluster/newEdit/components/multiVerComp/index.tsx
  taier-ui/src/pages/console/cluster/newEdit/index.tsx
Labels: bug

#327 [feat_task][taier-ui]support to get task type
  taier-ui/src/components/task/open.tsx
Labels: feature
